### ISSUE TITLE
No tag on this repository (and three others)

### ISSUE THREAD

**Issue by juliangilbey** [fabiospampinato/ansi-purge#1]
Hi @fabiospampinato, thanks for all this code!
I'm in the process of trying to package `tsex` for Debian, and I discovered that this repository, along with `get-current-package`, `isostore` and `tiny-levenshtein` do not have any tags.
Would it be possible to tag them all appropriately (with `1.0.0`)?  It will help us to ensure that we stay up-to-date with any changes.
Thanks!
Julian

**Comment by fabiospampinato** [comment]
Hi Julian. I'm not familiar with packaging for Debian, why would you want that? To not have to install NPM to use some packages?

> Would it be possible to tag them all appropriately (with 1.0.0)? It will help us to ensure that we stay up-to-date with any changes.

Yes, you are highlighting a bit of an issue I didn't pay attention too, I use a [tool](https://github.com/fabiospampinato/bump/) for bumping version numbers and tagging commits, the thing is until I bump the version number no commits are tagged 🤔 I should have thought about that. I can go through all my packages and add a tag for the initial release in each of them, but since I have like hundreds of them I don't not really have the time and patience right now to go through all this manual work.

**Comment by fabiospampinato** [comment]
In the meantime I've fixed the problem for `tsex` and all of its dependencies 🤪 hopefully that unblocks you.

**Comment by fabiospampinato** [comment]
Fixed across all my repos 😵‍💫 thanks!

**Comment by juliangilbey** [comment]
Aww, thanks @fabiospampinato!  I was going to suggest a short shell script to do the job, but you beat me to it (sorry for the slow reply).
